package storage

import (
	"context"
	"database/sql"
	"encoding/json"
	"errors"
	"fmt"
	"time"

	"github.com/google/uuid"
)

// migrateAgents creates the agent-related tables (agents, agent_versions) and
// ensures uniqueness is on (domain, team_id) rather than domain alone. All DDL
// is idempotent: CREATE TABLE IF NOT EXISTS + DROP/CREATE INDEX IF NOT EXISTS.
func (s *PostgresStore) migrateAgents(ctx context.Context) error {
	_, err := s.db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS agents (
			id            TEXT PRIMARY KEY,
			domain        TEXT NOT NULL,
			version       INT NOT NULL DEFAULT 1,
			status        TEXT NOT NULL DEFAULT 'draft',
			system_prompt TEXT NOT NULL DEFAULT '',
			instructions  TEXT NOT NULL DEFAULT '',
			anti_patterns TEXT NOT NULL DEFAULT '',
			source_refs   JSONB NOT NULL DEFAULT '[]',
			cluster_id    TEXT NOT NULL DEFAULT '',
			team_id       TEXT NOT NULL DEFAULT '',
			created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
		)
	`)
	if err != nil {
		return fmt.Errorf("create agents table: %w", err)
	}

	// Drop old single-column unique constraint if it exists (from legacy schema),
	// then create the composite (domain, team_id) unique index.
	// Both statements are idempotent: IF EXISTS / IF NOT EXISTS guards.
	_, err = s.db.ExecContext(ctx, `
		DO $$
		BEGIN
			-- Drop any unique constraint on domain alone (autogenerated name pattern).
			IF EXISTS (
				SELECT 1 FROM pg_constraint
				WHERE conrelid = 'agents'::regclass
				  AND contype = 'u'
				  AND conname IN ('agents_domain_key', 'agents_domain_unique')
			) THEN
				ALTER TABLE agents DROP CONSTRAINT IF EXISTS agents_domain_key;
				ALTER TABLE agents DROP CONSTRAINT IF EXISTS agents_domain_unique;
			END IF;
		END
		$$
	`)
	if err != nil {
		return fmt.Errorf("drop legacy agents domain constraint: %w", err)
	}

	_, err = s.db.ExecContext(ctx, `
		CREATE UNIQUE INDEX IF NOT EXISTS idx_agents_domain_team ON agents(domain, team_id)
	`)
	if err != nil {
		return fmt.Errorf("create agents domain+team index: %w", err)
	}

	_, err = s.db.ExecContext(ctx, `
		CREATE TABLE IF NOT EXISTS agent_versions (
			id            TEXT PRIMARY KEY,
			agent_id      TEXT NOT NULL REFERENCES agents(id),
			version       INT NOT NULL,
			system_prompt TEXT NOT NULL DEFAULT '',
			instructions  TEXT NOT NULL DEFAULT '',
			anti_patterns TEXT NOT NULL DEFAULT '',
			changelog     TEXT NOT NULL DEFAULT '',
			team_id       TEXT NOT NULL DEFAULT '',
			created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
			UNIQUE(agent_id, version)
		)
	`)
	if err != nil {
		return fmt.Errorf("create agent_versions table: %w", err)
	}

	return nil
}

// UpsertAgent inserts or updates an agent. If a.ID is empty, it looks up by
// (domain, team_id) so that each team upserts its OWN agent per domain.
// RenameDomain renames a domain across the team's entries, clusters, and agents
// in one transaction. See AgentStore.RenameDomain for semantics.
func (s *PostgresStore) RenameDomain(ctx context.Context, teamID, oldDomain, newDomain string) (RenameDomainResult, error) {
	var res RenameDomainResult
	tx, err := s.db.BeginTx(ctx, nil)
	if err != nil {
		return res, fmt.Errorf("begin tx: %w", err)
	}
	defer tx.Rollback()

	// Guard against the agents (domain, team_id) uniqueness constraint: refuse
	// the rename if the target domain is already taken by an agent in this team.
	var conflicts int
	if err := tx.QueryRowContext(ctx,
		`SELECT COUNT(*) FROM agents WHERE domain = $1 AND team_id = $2`,
		newDomain, teamID).Scan(&conflicts); err != nil {
		return res, fmt.Errorf("check domain conflict: %w", err)
	}
	if conflicts > 0 {
		return res, ErrDomainExists
	}

	targets := []struct {
		table string
		out   *int
	}{
		{"entries", &res.Entries},
		{"clusters", &res.Clusters},
		{"agents", &res.Agents},
	}
	for _, t := range targets {
		r, err := tx.ExecContext(ctx,
			fmt.Sprintf("UPDATE %s SET domain = $1, updated_at = NOW() WHERE domain = $2 AND team_id = $3", t.table),
			newDomain, oldDomain, teamID)
		if err != nil {
			return res, fmt.Errorf("rename domain in %s: %w", t.table, err)
		}
		n, _ := r.RowsAffected()
		*t.out = int(n)
	}

	if err := tx.Commit(); err != nil {
		return res, fmt.Errorf("commit: %w", err)
	}
	return res, nil
}

func (s *PostgresStore) UpsertAgent(ctx context.Context, a Agent) (string, error) {
	if a.ID == "" {
		existing, err := s.GetAgentByDomain(ctx, a.Domain, a.TeamID)
		if err != nil {
			return "", fmt.Errorf("lookup agent by domain: %w", err)
		}
		if existing != nil {
			a.ID = existing.ID
		} else {
			a.ID = uuid.NewString()
		}
	}

	if a.SourceRefs == nil {
		a.SourceRefs = []string{}
	}
	refsJSON, err := json.Marshal(a.SourceRefs)
	if err != nil {
		return "", fmt.Errorf("marshal source_refs: %w", err)
	}

	_, err = s.db.ExecContext(ctx, `
		INSERT INTO agents (id, domain, version, status, system_prompt, instructions, anti_patterns, source_refs, cluster_id, team_id)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
		ON CONFLICT (id) DO UPDATE SET
			version       = EXCLUDED.version,
			status        = EXCLUDED.status,
			system_prompt = EXCLUDED.system_prompt,
			instructions  = EXCLUDED.instructions,
			anti_patterns = EXCLUDED.anti_patterns,
			source_refs   = EXCLUDED.source_refs,
			cluster_id    = EXCLUDED.cluster_id,
			team_id       = EXCLUDED.team_id,
			updated_at    = NOW()
	`, a.ID, a.Domain, a.Version, string(a.Status),
		a.SystemPrompt, a.Instructions, a.AntiPatterns,
		string(refsJSON), a.ClusterID, a.TeamID)
	if err != nil {
		return "", fmt.Errorf("upsert agent: %w", err)
	}
	return a.ID, nil
}

// GetAgent returns the agent with the given ID, or nil if not found.
func (s *PostgresStore) GetAgent(ctx context.Context, id string) (*Agent, error) {
	row := s.db.QueryRowContext(ctx, `
		SELECT id, domain, version, status, system_prompt, instructions, anti_patterns,
		       source_refs, cluster_id, team_id, created_at, updated_at
		FROM agents WHERE id = $1
	`, id)
	a, err := scanAgentPG(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return a, nil
}

// GetAgentByDomain implements the AgentStore lookup semantics documented on the
// interface: team-scoped exact match first, legacy-row fallback, or unscoped
// when teamID is empty (dev/single-tenant).
func (s *PostgresStore) GetAgentByDomain(ctx context.Context, domain, teamID string) (*Agent, error) {
	if teamID == "" {
		// Dev / single-tenant: return any matching agent.
		row := s.db.QueryRowContext(ctx, `
			SELECT id, domain, version, status, system_prompt, instructions, anti_patterns,
			       source_refs, cluster_id, team_id, created_at, updated_at
			FROM agents WHERE domain = $1 LIMIT 1
		`, domain)
		a, err := scanAgentPG(row)
		if err != nil {
			if errors.Is(err, sql.ErrNoRows) {
				return nil, nil
			}
			return nil, fmt.Errorf("get agent by domain: %w", err)
		}
		return a, nil
	}

	// Exact team match.
	row := s.db.QueryRowContext(ctx, `
		SELECT id, domain, version, status, system_prompt, instructions, anti_patterns,
		       source_refs, cluster_id, team_id, created_at, updated_at
		FROM agents WHERE domain = $1 AND team_id = $2
	`, domain, teamID)
	a, err := scanAgentPG(row)
	if err != nil && !errors.Is(err, sql.ErrNoRows) {
		return nil, fmt.Errorf("get agent by domain (team): %w", err)
	}
	if a != nil {
		return a, nil
	}

	// Legacy fallback: row created before per-team scoping (team_id='').
	row = s.db.QueryRowContext(ctx, `
		SELECT id, domain, version, status, system_prompt, instructions, anti_patterns,
		       source_refs, cluster_id, team_id, created_at, updated_at
		FROM agents WHERE domain = $1 AND team_id = ''
	`, domain)
	a, err = scanAgentPG(row)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, nil
		}
		return nil, fmt.Errorf("get agent by domain (legacy): %w", err)
	}
	return a, nil
}

// ListAgents returns agents ordered by domain ascending, filtered by teamID when non-empty.
func (s *PostgresStore) ListAgents(ctx context.Context, teamID string) ([]Agent, error) {
	query := `
		SELECT id, domain, version, status, system_prompt, instructions, anti_patterns,
		       source_refs, cluster_id, team_id, created_at, updated_at
		FROM agents`
	var args []any
	if teamID != "" {
		query += " WHERE team_id = $1"
		args = append(args, teamID)
	}
	query += " ORDER BY domain ASC"
	rows, err := s.db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, fmt.Errorf("list agents: %w", err)
	}
	defer rows.Close()

	var agents []Agent
	for rows.Next() {
		a, err := scanAgentPG(rows)
		if err != nil {
			return nil, fmt.Errorf("scan agent: %w", err)
		}
		agents = append(agents, *a)
	}
	return agents, rows.Err()
}

// PublishAgent sets the agent's status to 'published'.
func (s *PostgresStore) PublishAgent(ctx context.Context, id string) error {
	res, err := s.db.ExecContext(ctx,
		`UPDATE agents SET status = 'published', updated_at = NOW() WHERE id = $1`, id)
	if err != nil {
		return fmt.Errorf("publish agent: %w", err)
	}
	if n, _ := res.RowsAffected(); n == 0 {
		return fmt.Errorf("agent %q: %w", id, ErrNotFound)
	}
	return nil
}

// StoreAgentVersion inserts a versioned snapshot of an agent. Idempotent on (agent_id, version).
func (s *PostgresStore) StoreAgentVersion(ctx context.Context, v AgentVersion) error {
	v.ID = uuid.NewString()
	_, err := s.db.ExecContext(ctx, `
		INSERT INTO agent_versions (id, agent_id, version, system_prompt, instructions, anti_patterns, changelog)
		VALUES ($1, $2, $3, $4, $5, $6, $7)
		ON CONFLICT (agent_id, version) DO NOTHING
	`, v.ID, v.AgentID, v.Version, v.SystemPrompt, v.Instructions, v.AntiPatterns, v.Changelog)
	if err != nil {
		return fmt.Errorf("store agent version: %w", err)
	}
	return nil
}

// ListAgentVersions returns all version records for the given agent, ordered by version ascending.
func (s *PostgresStore) ListAgentVersions(ctx context.Context, agentID string) ([]AgentVersion, error) {
	rows, err := s.db.QueryContext(ctx, `
		SELECT id, agent_id, version, system_prompt, instructions, anti_patterns, changelog, created_at
		FROM agent_versions WHERE agent_id = $1 ORDER BY version ASC
	`, agentID)
	if err != nil {
		return nil, fmt.Errorf("list agent versions: %w", err)
	}
	defer rows.Close()

	var versions []AgentVersion
	for rows.Next() {
		var v AgentVersion
		var createdAt time.Time
		if err := rows.Scan(
			&v.ID, &v.AgentID, &v.Version,
			&v.SystemPrompt, &v.Instructions, &v.AntiPatterns,
			&v.Changelog, &createdAt,
		); err != nil {
			return nil, fmt.Errorf("scan agent version: %w", err)
		}
		v.CreatedAt = createdAt
		versions = append(versions, v)
	}
	return versions, rows.Err()
}

// scanAgentPG scans an agent row from the PostgreSQL agents table.
func scanAgentPG(row rowScanner) (*Agent, error) {
	var a Agent
	var refsRaw []byte
	var createdAt, updatedAt time.Time
	err := row.Scan(
		&a.ID, &a.Domain, &a.Version, &a.Status,
		&a.SystemPrompt, &a.Instructions, &a.AntiPatterns,
		&refsRaw, &a.ClusterID, &a.TeamID, &createdAt, &updatedAt,
	)
	if err != nil {
		return nil, err
	}
	if err := json.Unmarshal(refsRaw, &a.SourceRefs); err != nil {
		a.SourceRefs = []string{}
	}
	a.CreatedAt = createdAt
	a.UpdatedAt = updatedAt
	return &a, nil
}
